### ISSUE TITLE
#2 - Structure de contrôle

### ISSUE THREAD

**Issue by StevenGam** [Maxime155/Projet#3]
if a == b
   and c == d:
    print('yes')

Alors que ceci est correct (et équivalent à la sémantique entendue):

if (a == b
    and c == d):
    print('yes')

Structures de contrôle

Source : https://docs.python.org/3.5/tutorial/controlflow.html
if... else

La seule construction conditionnelle existante en Python est if... elif... else.... Toutes les branches sont optionnelles, à l'exception du if, il peut y avoir un nombre quelconque de elif, mais un seul else à la fin.

if a == b == c:
    print('égaux')
elif a <= b <= c  or  c <= b <= a:
    print 'b au milieu'
elif b <= a <= c  or  c <= a <= b:
    print('a au milieu')
else:
    print('c au milieu')

Boucle for... in

Il existe deux types de boucles en Python. La plus couramment utilisée est le for... in qui permet de parcourir les éléments d'une liste.

**Comment by Mostafa-lab10** [comment]
Ok pour moi

**Comment by Maxime155** [comment]
ça me parait bon
